services:
  zkzzk:
    image: d3vle0/zkzzk:latest
    container_name: zkzzk
    environment:
      - TZ=${SERVER_TZ:-Asia/Seoul} # Change this to your timezone (e.g., Europe/London, America/New_York)
    ports:
      - "10000:3000"
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
