services:
  zkzzk-app:
    image: d3vle0/zkzzk:latest
    container_name: zkzzk-app
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - TZ=Asia/Seoul
      - DATABASE_URL=file:/app/backend/data/database.db
    volumes:
      - ./data:/app/backend/data
      - ./downloads:/app/downloads
